### ISSUE TITLE
Game crashes with this addon

### ISSUE THREAD

**Issue by EnderHacker0** [AntiCope/meteor-rejects#154]
### Describe the bug

I put the jar file into my mods folder and started the game and it crashes.

### Crashlog

java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/gui/widgets/pressable/WFavorite
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at anticope.rejects.MeteorRejectsAddon.onInitialize(MeteorRejectsAddon.java:99)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:94)
	at net.minecraft.class_310.handler$zep004$onInit(class_310.java:7536)
	at net.minecraft.class_310.<init>(class_310.java:637)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: meteordevelopment.meteorclient.gui.widgets.pressable.WFavorite
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at anticope.rejects.MeteorRejectsAddon.onInitialize(MeteorRejectsAddon.java:99)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:94)
	at net.minecraft.class_310.handler$zep004$onInit(class_310.java:7536)
	at net.minecraft.class_310.<init>(class_310.java:637)

### Steps to reproduce

1.Put the jar file into the mods folder
2.Launch the game
3.Game crashes after the game window appear

### Operating System

Windows

### Meteor Version

0.4.7

### Minecraft Version

1.18.1

### Other mods

```plaintext
1.Sodium
2.Meteor Client
3.MultiConnect
```

**Comment by C10udburst** [comment]
outdated meteor. use latest versions

**Comment by I-Got-You-Dead** [comment]
L
