### ISSUE TITLE
[Bug] Game crashes

### ISSUE THREAD

**Issue by B0r1sYT** [AntiCope/meteor-rejects#157]
### Describe the bug

When i enable a module from meteor rejects the game just simply crashes any way to fix this?

### Crashlog

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 31.08.22, 19:39
Description: mouseReleased event handler

meteordevelopment.orbit.NoLambdaFactoryException: No registered lambda listener for 'anticope.rejects.modules.ChatBot'.
	at meteordevelopment.orbit.EventBus.getLambdaFactory(EventBus.java:182)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:160)
	at meteordevelopment.orbit.EventBus.lambda$getListeners$2(EventBus.java:140)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:152)
	at meteordevelopment.orbit.EventBus.unsubscribe(EventBus.java:108)
	at meteordevelopment.meteorclient.systems.modules.Module.toggle(Module.java:79)
	at meteordevelopment.meteorclient.gui.themes.meteor.widgets.WMeteorModule.onPressed(WMeteorModule.java:59)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:27)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25406(WidgetScreen.java:134)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.orbit.EventBus.getLambdaFactory(EventBus.java:182)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:160)
	at meteordevelopment.orbit.EventBus.lambda$getListeners$2(EventBus.java:140)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:152)
	at meteordevelopment.orbit.EventBus.unsubscribe(EventBus.java:108)
	at meteordevelopment.meteorclient.systems.modules.Module.toggle(Module.java:79)
	at meteordevelopment.meteorclient.gui.themes.meteor.widgets.WMeteorModule.onPressed(WMeteorModule.java:59)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:27)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25406(WidgetScreen.java:134)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: meteordevelopment.meteorclient.gui.screens.ModulesScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Pyrexic'/4019, l='ClientLevel', x=194.89, y=44.00, z=101.60]]
	Chunk stats: 841, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,44,92), Section: (at 8,12,12 in 0,2,5; chunk contains blocks 0,-64,80 to 15,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 51913 game time, 12200 day time
	Server brand: Minehut/Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 661419288 bytes (630 MiB) / 1509949440 bytes (1440 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-8350 Eight-Core Processor           
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 4,03
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 23021,54
	Virtual memory used (MB): 14992,10
	Swap memory total (MB): 6656,00
	Swap memory used (MB): 0,00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 

-- Meteor Client --
Version: 0.5.0
Dev Build: 1559

[Combat]:
auto-totem
criticals

[Player]:
air-place

[Movement]:
anti-void
elytra-fly
no-fall
safe-walk
velocity

[Render]:
better-tooltips
esp
item-highlight
nametags
search
storage-esp
tracers

[Misc]:
middle-click-friend
server-spoof

[Rejects]:
chat-bot

### Steps to reproduce

1.Go into a Server
2.Enable a Module
3.Crash
...

### Operating System

Windows

### Addon Version

1.19

### Meteor Version

1.19

### Minecraft Version

1.19

**Comment by C10udburst** [comment]
update your meteor clinet
