### ISSUE TITLE
[Bug] Minecraft crashes when initializing meteor addons

### ISSUE THREAD

**Issue by nbedless** [AntiCope/meteor-rejects#195]
### Describe the bug

Using meteor addons causes minecarft to crash during initialising phase

### Crashlog

[14:12:18] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[14:12:18] [ForkJoinPool-1-worker-3/WARN]: Mod com_seedfinding_mc_seed uses the version 5518e3ba3ee567fb0b51c15958967f70a6a19e02 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '5518e3ba3ee567fb0b51c15958967f70a6a19e02'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:12:19] [ForkJoinPool-1-worker-1/WARN]: Mod com_seedfinding_mc_noise uses the version a6ab8e6c688491829f8d2adf845392da22ef8e9c which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'a6ab8e6c688491829f8d2adf845392da22ef8e9c'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:12:19] [ForkJoinPool-1-worker-3/WARN]: Mod com_seedfinding_mc_math uses the version 0eb505174da8a92550f8ec6efe254e0fa936cc0d which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0eb505174da8a92550f8ec6efe254e0fa936cc0d'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:12:19] [ForkJoinPool-1-worker-3/WARN]: Mod com_seedfinding_mc_terrain uses the version 9e937ddb838e28e79423c287fa18b1ce66f061d7 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '9e937ddb838e28e79423c287fa18b1ce66f061d7'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:12:19] [ForkJoinPool-1-worker-7/WARN]: Mod com_seedfinding_mc_reversal uses the version ca64c0890c106f1a2207623c316fce86f250b918 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'ca64c0890c106f1a2207623c316fce86f250b918'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:12:19] [ForkJoinPool-1-worker-1/WARN]: Mod com_seedfinding_mc_core uses the version d685a37f0a466d4bf800e7f285daf9ef73c81678 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'd685a37f0a466d4bf800e7f285daf9ef73c81678'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:12:19] [ForkJoinPool-1-worker-2/WARN]: Mod com_seedfinding_mc_biome uses the version b2271807a047bb43ac60c8c20ad47e315f19b9a6 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'b2271807a047bb43ac60c8c20ad47e315f19b9a6'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:12:19] [ForkJoinPool-1-worker-5/WARN]: Mod com_seedfinding_mc_feature uses the version c29fd1fcd746e14c1bcdb127da3113ba273db1fd which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'c29fd1fcd746e14c1bcdb127da3113ba273db1fd'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:12:19] [main/INFO]: Loading 73 mods:
	- baritone-meteor 1.19.3-SNAPSHOT via meteor-client
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 9.0.94 via seedcrackerx
	- com_seedfinding_latticg 1.6 via seedcrackerx
	- com_seedfinding_mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6 via seedcrackerx
	- com_seedfinding_mc_core d685a37f0a466d4bf800e7f285daf9ef73c81678 via seedcrackerx
	- com_seedfinding_mc_feature c29fd1fcd746e14c1bcdb127da3113ba273db1fd via seedcrackerx
	- com_seedfinding_mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d via seedcrackerx
	- com_seedfinding_mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c via seedcrackerx
	- com_seedfinding_mc_reversal ca64c0890c106f1a2207623c316fce86f250b918 via seedcrackerx
	- com_seedfinding_mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02 via seedcrackerx
	- com_seedfinding_mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7 via seedcrackerx
	- fabric-api 0.69.1+1.19.3
	- fabric-api-base 0.4.19+8d1895cf85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.18+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.0.0+689f5e7185 via fabric-api
	- fabric-block-api-v1 1.0.3+12bfe4ea85 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.28+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.9+49abcf7e85 via fabric-api
	- fabric-command-api-v1 1.2.19+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.1.15+49abcf7e85 via fabric-api
	- fabric-commands-v0 0.2.36+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.44+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.4.12+49abcf7e85 via fabric-api
	- fabric-convention-tags-v1 1.2.0+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.12+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.1+112a38be85 via fabric-api
	- fabric-dimensions-v1 2.1.39+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.5+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.37+422b77fb85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.39+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.28+2894d6df85 via fabric-api
	- fabric-item-api-v1 2.1.5+4d2c606385 via fabric-api
	- fabric-item-group-api-v1 2.1.8+d3d735d085 via fabric-api
	- fabric-key-binding-api-v1 1.0.28+aaaf9d3385 via fabric-api
	- fabric-keybindings-v0 0.2.26+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.8+2894d6df85 via fabric-api
	- fabric-loot-api-v2 1.1.18+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.22+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.12+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.29+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.25+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.14+d9ac3c3985 via fabric-api
	- fabric-networking-v0 0.3.31+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.2.0+e9dee00485 via fabric-api
	- fabric-particles-v1 1.0.18+fbde993d85 via fabric-api
	- fabric-registry-sync-v0 2.0.1+2608564685 via fabric-api
	- fabric-renderer-api-v1 2.1.0+2063beff85 via fabric-api
	- fabric-renderer-indigo 0.6.23+11ba9c3b85 via fabric-api
	- fabric-renderer-registries-v1 3.2.28+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.23+48349a3f85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.16+3067f46385 via fabric-api
	- fabric-rendering-v0 1.1.31+df3654b385 via fabric-api
	- fabric-rendering-v1 1.11.7+49abcf7e85 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.0+280be3ab85 via fabric-api
	- fabric-resource-loader-v0 0.10.3+a10d22bd85 via fabric-api
	- fabric-screen-api-v1 1.0.39+1d4d0b5785 via fabric-api
	- fabric-screen-handler-api-v1 1.3.10+689f5e7185 via fabric-api
	- fabric-sound-api-v1 1.0.6+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.12+82a2701785 via fabric-api
	- fabric-transitive-access-wideners-v1 2.1.0+0efcd39b85 via fabric-api
	- fabricloader 0.14.12
	- java 17
	- litematica 0.13.0
	- lithium 0.10.4
	- malilib 0.14.0
	- meteor-client 0.5.2-1741
	- meteor-rejects 0.2
	- minecraft 1.19.3
	- phosphor 0.8.1
	- seedcrackerx 2.13.1-test
	- seedcrackerx-api 2.10.1 via meteor-rejects
	- sodium 0.4.6+build.20
[14:12:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/me/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:12:19] [main/INFO]: Compatibility level set to JAVA_17
[14:12:20] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 0 override(s) found
[14:12:20] [main/INFO]: Loaded configuration file for Sodium: 30 options available, 0 override(s) found
[14:12:25] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[14:12:35] [main/INFO]: Building optimized datafixer
[14:12:47] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:12:49] [Render thread/INFO]: Setting user: oRampage
[14:12:52] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[14:12:55] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[14:12:58] [Render thread/WARN]: Missing metadata in pack file/!         §9Hopqings §3§lFaith §7[§bRevamp§7].zip
[14:12:58] [Render thread/WARN]: Missing metadata in pack file/!       )5)lCooldudes )615k )3Pack - War V2 Revamp Swords.zip
[14:12:58] [Render thread/ERROR]: Failed to open pack C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\!       §5§lCooldudes §615k §3Pack.zip
java.util.zip.ZipException: invalid CEN header (bad entry name)
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598) ~[?:?]
	at java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1209) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1537) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:186) ~[?:?]
	at net.minecraft.class_3258.method_14399(class_3258.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_3258.method_14391(class_3258.java:72) ~[client-intermediary.jar:?]
	at net.minecraft.class_3258.method_14410(class_3258.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/!       §5§lCooldudes §615k §3Pack.zip
[14:12:59] [Render thread/INFO]: Found non-pack entry 'C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\!   ALPHASTAR', ignoring
[14:12:59] [Render thread/INFO]: Found non-pack entry 'C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\!   ALPHASTAR.rar', ignoring
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/!uh v2.zip
[14:12:59] [Render thread/INFO]: Found non-pack entry 'C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\50 Fanmade pack', ignoring
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/50 Fanmade pack .zip
[14:12:59] [Render thread/ERROR]: Couldn't load pack metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at net.minecraft.class_3518.method_47993(class_3518.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:523) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15274(class_3518.java:585) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15255(class_3518.java:593) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14392(class_3255.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1648) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1025) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_47993(class_3518.java:516) ~[client-intermediary.jar:?]
	... 18 more
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/A Simple PvP Experience!(Beta)
[14:12:59] [Render thread/INFO]: Found non-pack entry 'C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\bejinxed private pack.rar', ignoring
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/blazingpack_1.8.8.zip
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/blue pack inside.zip
[14:12:59] [Render thread/INFO]: Found non-pack entry 'C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\ColdDeadlyCombo Custom Pack', ignoring
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/ColdDeadlyCombo Custom Pack.zip
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/Dragonfruit 32x Blue (Recolored).zip
[14:12:59] [Render thread/ERROR]: Couldn't load pack metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at net.minecraft.class_3518.method_47993(class_3518.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:523) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15274(class_3518.java:585) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15255(class_3518.java:593) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14392(class_3255.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1648) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1025) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_47993(class_3518.java:516) ~[client-intermediary.jar:?]
	... 18 more
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/lastro x modifier revamp.zip
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/The Caterpack.zip
[14:12:59] [Render thread/ERROR]: Couldn't load pack metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at net.minecraft.class_3518.method_47993(class_3518.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:523) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15274(class_3518.java:585) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15255(class_3518.java:593) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14392(class_3255.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1648) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1025) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_47993(class_3518.java:516) ~[client-intermediary.jar:?]
	... 18 more
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/Vene 32x.zip
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/Vyrinnn Revamp by Childish.zip
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/§3Rampqge Edit §bparticles - Copy.zip
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/§3Rampqge Edit §bparticles.zip
[14:12:59] [Render thread/INFO]: Found non-pack entry 'C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\§5Purpleds Default Edit v1', ignoring
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/§5Purpleds Default Edit v1.zip
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/§5Telly 60k Pack.zip
[14:12:59] [Render thread/INFO]: Found non-pack entry 'C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\§bCDC §7Custom §8Pack (1)', ignoring
[14:12:59] [Render thread/INFO]: Found non-pack entry 'C:\Users\me\AppData\Roaming\.minecraft\resourcepacks\§bCDC §7Custom §8Pack (1).rar', ignoring
[14:12:59] [Render thread/WARN]: Missing metadata in pack file/§bRKYfault§3[16x] §2Cheetahh Edit.zip
[14:13:00] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[14:13:03] [Render thread/INFO]: Narrator library for x64 successfully loaded
[14:13:04] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (Cloth Config v9, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Litematica, Lithium, MaLiLib, Meteor Client, Meteor Rejects, Phosphor, SeedCrackerX, SeedCrackerX API, Sodium)
[14:13:05] [Render thread/INFO]: [STDOUT]: Baritone settings file not found, resetting.
[14:13:09] [Render thread/INFO]: Initializing Meteor Client
[14:13:12] [Render thread/INFO]: Reflections took 2181 ms to scan 1 urls, producing 17 keys and 795 values
[14:13:13] [Render thread/INFO]: Found 4 font families.
[14:13:14] [Render thread/INFO]: Reflections took 59 ms to scan 1 urls, producing 8 keys and 102 values
[14:13:18] [Render thread/INFO]: Initializing Meteor Rejects Addon

### Steps to reproduce

1. launch frabic loader 1.19.3
2. Use (meteor latest dev version, sodium, lithium and phosphor 
3.launch game
...

### Operating System

Windows

### Meteor Version

dev build 0.5.2

### Minecraft Version

1.19.3

### Other mods

```plaintext
1.Sodium
2.Lithium
3.Phosphor
...
```

**Comment by C10udburst** [comment]
this doesnt contain anything about a crash

**Comment by C10udburst** [comment]
It looks like you are running Minecraft with the Fabric Mod Loader and some mods installed. The log file you provided contains a list of resource packs that could not be loaded due to various issues, such as missing metadata or invalid file structure. It also shows that there are some problems with invalid escape sequences in the pack descriptions of some resource packs.

If you are experiencing issues with your resource packs or mods, you might try removing any packs that are causing problems and ensure that your mods are up to date and compatible with your version of Minecraft and the Fabric Mod Loader. You may also want to try resetting your Minecraft configuration files to their default state, as this can sometimes resolve issues with mods and resource packs.
