### ISSUE TITLE
[Bug] crash when playing 1.19.4

### ISSUE THREAD

**Issue by ItsEgmxn** [AntiCope/meteor-rejects#249]
### Describe the bug

it just crashes when i try to open the game

### Crashlog

java.lang.NoSuchMethodError: 'it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap meteordevelopment.meteorclient.utils.Utils.asO2BMap(java.lang.Object[])'
	at anticope.rejects.modules.InteractionMenu.<init>(InteractionMenu.java:32)
	at anticope.rejects.MeteorRejectsAddon.onInitialize(MeteorRejectsAddon.java:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:121)
	at net.minecraft.class_310.handler$bpg01a$meteor-client$onInit(class_310.java:11549)
	at net.minecraft.class_310.<init>(class_310.java:683)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at anticope.rejects.modules.InteractionMenu.<init>(InteractionMenu.java:32)
	at anticope.rejects.MeteorRejectsAddon.onInitialize(MeteorRejectsAddon.java:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:121)
	at net.minecraft.class_310.handler$bpg01a$meteor-client$onInit(class_310.java:11549)
	at net.minecraft.class_310.<init>(class_310.java:683)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Gelişmiş Windows 32 Tabanlı API:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Kullanıcı Deneyimi Denetimleri Kitaplığı:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Şifreleme API32:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		ColorAdapterClient.dll:Microsoft Color Adapter Client:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.19041.2193:Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.19041.546:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS İstemcisi API DLL'si:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Yardımcı Uygulaması DLL Kitaplığı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.2673 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Win32 Kernel çekirdek bileşeni:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Win32 Kernel çekirdek bileşeni:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API'sı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		MSACM32.dll:Microsoft ACM Ses Filtresi:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:10.0.19041.2251 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2304.8 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Windows için Microsoft OLE:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		PROPSYS.dll:Microsoft Özellik Sistemi:7.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Uzaktan Yordam Çağrısı Çalıştırma Zamanı Modülü:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		SETUPAPI.dll:Windows Kur API:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Ortak Dll'i:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Çok Kullanıcılı Windows USER API İstemci DLL'si:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Hizmetleri:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32 Bit DLL'si:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Kilitleme İlkesi:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Uygulama Uyumluluğu İstemci Kitaplığı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		atiadlxx.dll:ADL:7.20.10.1382:Advanced Micro Devices, Inc.
		atig6pxx.dll:atiglpxx.dll:8.14.01.6564:Advanced Micro Devices, Inc. 
		atig6txx.dll:atigktxx.dll:8.14.01.6564:Advanced Micro Devices, Inc. 
		atio6axx.dll:AMD OpenGL driver:8.14.11000.13596:Advanced Micro Devices, Inc.
		awt.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		bcrypt.dll:Windows Şifreleme Temel Elemanları Kitaplığı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.2486 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Windows için Microsoft COM:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP İstemci Hizmeti:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 İstemcisi:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft Masaüstü Pencere Yöneticisi API'si:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		dxva2.dll:DirectX Video Acceleration 2.0 DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fastprox.dll:WMI Custom Marshaller:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec Kullanıcı Modu API'si:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jna6512347818414144584.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		mscms.dll:Microsoft Renk Eşleştirme Sistemi DLL'si:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		msdmo.dll:DMO Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Servis Sağlayıcı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-posta Adlandırma Shim Sağlayıcısı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Yönlendiricisi:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		ntdll.dll:NT Katmanı DLL’si:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA sağlayıcı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:10.0.19041.2193 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows Sistem Performans Nesneleri DLL:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Ad Alanı Sağlayıcısı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sapi.dll:Speech API:5.3.24006.00 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Kabuk Hafif Hizmet Programı Kitaplığı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Kitaplığı:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		wbemcomn.dll:WMI:10.0.19041.1566 (WinBuild.160101.0800):Microsoft Corporation
		wbemprox.dll:WMI:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		wbemsvc.dll:WMI:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		win32u.dll:Win32u:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Depolama API:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		winmmbase.dll:Base Multimedia Extension API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Temel Türler DLL'si:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:10.0.19041.2965 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Steps to reproduce

open the game

### Operating System

Windows

### Addon Version

0.2

### Meteor Version

0.5.3 1843

### Minecraft Version

1.19.4

### Other mods

```plaintext
1.
2.
3.
...
```

**Comment by FoxyDrew** [comment]
Can confirm this issue occurs with no other mods installed, and worked fine with previous dev builds of meteor-client. Broken in 0.5.3-1843
