### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by scouttiger** [AntiCope/meteor-rejects#65]
### Describe the bug

Instant crash at initialization. 

stacktrace:
-- Head --
Thread: Render thread
Stacktrace:
	at cloudburst.rejects.MeteorRejectsAddon.onInitialize(MeteorRejectsAddon.java:54)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:124)
	at net.minecraft.class_310.handler$zob006$onInit(class_310.java:14087)
	at net.minecraft.class_310.<init>(class_310.java:637)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

Process crashed with exit code -1

### Steps to reproduce

```plaintext
1. Start the client with the mod installed (fabric 1.17.1)
```

### Operating System

Windows

### Rejects Version

0.0.4

### Meteor Version

0.4.5

### Minecraft Version

1.17.1

### Other mods

```plaintext
1.unobtainables
2.advancementinfo
3.anycapes
4.audiooutput
5.betterf3
6.betterpingdisplay
7.cleardespawn
8.unsuspiciousstew
9.litematica
10.malilib (library)
11.minihud
12.modmenu
13.multiconnect
14.notes
15.sheepconsistency
16.signcopy
17.skin-swapper
18.sodium
19.stendhal
20.surrogate
21.watson
22.xaeros,both mini and worldmap
```

**Comment by scouttiger** [comment]
Error: java.lang.NoClassDefFoundError: meteordevelopment/starscript/utils/StarscriptError

**Comment by C10udburst** [comment]
update meteor client to the latest [devbuild](https://meteorclient.com/download?devBuild=latest)
