### ISSUE TITLE
[Bug] Crash whenever I join a server

### ISSUE THREAD

**Issue by snnwer** [AntiCope/meteor-rejects#70]
### Describe the bug

no idea why, have the latest dev build
[21:34:24] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "anticope.rejects.modules.Rendering.getShaderEffect()" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get(java.lang.Class)" is null
	at net.minecraft.class_757.redirect$zid000$renderShader(class_757.java:1507) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]

### Steps to reproduce

```plaintext
1. install latest meteor dev build
2. install latest meteor rejects
```

### Operating System

Windows

### Rejects Version

#3d7d4ca

### Meteor Version

0.4.6 build 1320

### Minecraft Version

1.17

### Other mods

```plaintext
1. sodium
2. fabric api
3. multiconnect
...
```

**Comment by StormyBytes** [comment]
I updated the addon to the latest dev build on 2e1abe481e81302eca4a0408ed6e704ac6674a48

**Comment by StormyBytes** [comment]
@snnwer does this crash still happen?

**Comment by snnwer** [comment]
> @snnwer does this crash still happen?

no, fixed, thank you
